# Generated by Django 3.0.8 on 2020-09-07 00:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(help_text='Enter The Car Brand Name', max_length=100)),
                ('banner_image', models.ImageField(help_text='Upload The Image For The Banner', upload_to='images/banner/')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text='Enter The Model Name', max_length=100)),
                ('model_image', models.ImageField(blank=True, help_text='Upload The Image For The Car Model', upload_to='images/model/')),
                ('brand', models.ForeignKey(help_text='Select The CarBrand', on_delete=django.db.models.deletion.CASCADE, to='product.CarBrand')),
            ],
        ),
        migrations.CreateModel(
            name='CarEngine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_name', models.CharField(help_text='Enter The Year Name', max_length=100)),
                ('engine_name', models.CharField(help_text='Enter The Engine Name', max_length=100)),
                ('engine_type', models.CharField(blank=True, choices=[('gas', 'Gasoline'), ('disel', 'Diesel Micro Hybrid'), ('hybrid', 'Hybrid')], help_text='Enter The Engine Type', max_length=100)),
                ('engine_status', models.CharField(blank=True, choices=[('new', 'New'), ('indev', 'In development')], help_text='Enter The Engine Status', max_length=100, null=True)),
                ('eco_torque_origin', models.IntegerField(blank=True, help_text='Enter The Origin Value(Nm)', null=True)),
                ('eco_torque_difference', models.IntegerField(blank=True, help_text='Enter The Difference Value(Nm)', null=True)),
                ('eco_estimated_fuel_reduction', models.IntegerField(blank=True, help_text='Enter The Estimated Fuel Reduction(%)', null=True)),
                ('eco_price', models.IntegerField(blank=True, help_text='Enter The Price(€)', null=True)),
                ('eco_description', models.TextField(blank=True, help_text='Enter The Description For the ECO', null=True)),
                ('stage1_torque_origin', models.IntegerField(blank=True, help_text='Enter The Origin Value(Nm)', null=True)),
                ('stage1_torque_difference', models.IntegerField(blank=True, help_text='Enter The Difference Value(Nm)', null=True)),
                ('stage1_power_origin', models.IntegerField(blank=True, help_text='Enter The Origin Value(hp)', null=True)),
                ('stage1_power_difference', models.IntegerField(blank=True, help_text='Enter The Difference Value(hp)', null=True)),
                ('stage1_price', models.IntegerField(blank=True, help_text='Enter The Price(€)', null=True)),
                ('stage1_description', models.TextField(blank=True, help_text='Enter The Description For the ECO', null=True)),
                ('stage2_torque_origin', models.IntegerField(blank=True, help_text='Enter The Origin Value(Nm)', null=True)),
                ('stage2_torque_difference', models.IntegerField(blank=True, help_text='Enter The Difference Value(Nm)', null=True)),
                ('stage2_power_origin', models.IntegerField(blank=True, help_text='Enter The Origin Value(hp)', null=True)),
                ('stage2_power_difference', models.IntegerField(blank=True, help_text='Enter The Difference Value(hp)', null=True)),
                ('stage2_price', models.IntegerField(blank=True, help_text='Enter The Price(€)', null=True)),
                ('stage2_description', models.TextField(blank=True, help_text='Enter The Description For the ECO', null=True)),
                ('dsg_torque_origin', models.IntegerField(blank=True, help_text='Enter The Origin Value(Nm)', null=True)),
                ('dsg_torque_difference', models.IntegerField(blank=True, help_text='Enter The Difference Value(Nm)', null=True)),
                ('model', models.ForeignKey(help_text='Select The CarModel', on_delete=django.db.models.deletion.CASCADE, to='product.CarModel')),
            ],
        ),
    ]
