# Generated by Django 3.0.8 on 2020-07-26 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import submission.fields
import submission.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car_vin_number', models.CharField(max_length=100)),
                ('car_brand', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_build', models.CharField(max_length=100)),
                ('engine_type', models.CharField(max_length=100)),
                ('engine_power', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('tuning_level', models.CharField(max_length=100)),
                ('user_message', models.TextField(blank=True, max_length=100, null=True)),
                ('reading_method', models.CharField(blank=True, max_length=100, null=True)),
                ('ecu_type', models.CharField(blank=True, max_length=100, null=True)),
                ('car_plate_num', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('file1', submission.fields.ContentTypeRestrictedFileField(blank=True, upload_to=submission.models.case_upload_location)),
                ('file2', submission.fields.ContentTypeRestrictedFileField(blank=True, upload_to=submission.models.case_upload_location)),
                ('file3', submission.fields.ContentTypeRestrictedFileField(blank=True, upload_to=submission.models.case_upload_location)),
                ('file4', submission.fields.ContentTypeRestrictedFileField(blank=True, upload_to=submission.models.case_upload_location)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
